x-airflow-environment: &airflow-environment
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
  AIRFLOW__CORE__FERNET_KEY: ''
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
  AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
  AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
  AIRFLOW__WEBSERVER__SECRET_KEY: 'your_airflow_webserver_sec_key'
  AIRFLOW_CONN_CLICKHOUSE_DEFAULT: 'clickhouse://default:@olap_db:9000/bionicpro'
  # Переменные для подключения к ClickHouse
  CLICKHOUSE_HOST: olap_db
  CLICKHOUSE_PORT: 9000
  CLICKHOUSE_DB: bionicpro
  CLICKHOUSE_USER: default
  CLICKHOUSE_PASSWORD: default_pwd
  _PIP_ADDITIONAL_REQUIREMENTS: ''
  AIRFLOW_INPUT_DIR: '/opt/airflow/dag-inputs'
  HOSTNAME: airflow

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: airflow/Dockerfile
  environment:
    *airflow-environment
  volumes:
    - ./dags:/opt/airflow/dags
    - ./dags/sql:/opt/airflow/dags/sql
    - ./requirements.txt:/opt/airflow/requirements.txt
    - ./data:/opt/airflow/sample_files
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy
    olap_db:
      condition: service_healthy
  networks:
    - bionicpro-network

services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - bionicpro-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak_user -d keycloak_db"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      # Включаем HTTP
      KC_HTTP_ENABLED: "true"
      # ВАЖНО: Отключаем strict-режим полностью
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      # Принудительно заставляем админку работать по HTTP
      # KC_HOSTNAME_ADMIN_URL: http://localhost:8082
    command: >
      start-dev
      --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8082:8080"
    depends_on:
      keycloak_db:
        condition: service_healthy
      openldap:
        condition: service_started
    networks:
      - bionicpro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_KEYCLOAK_URL: http://localhost:8082
      REACT_APP_KEYCLOAK_REALM: reports-realm
      REACT_APP_KEYCLOAK_CLIENT_ID: reports-frontend
    networks:
      - bionicpro-network
  
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    command: --copy-service
    volumes:
      - ./ldap/config.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
    environment:
      - LDAP_ORGANISATION=example-com
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_READONLY_USER=false
    ports:
      - "389:389"
      - "636:636"
    networks:
      - bionicpro-network
    healthcheck:
      test: ["CMD", "ldapsearch", "-x", "-H", "ldap://localhost:389", "-b", "dc=example,dc=com", "-D", "cn=admin,dc=example,dc=com", "-w", "admin", "(objectClass=*)"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
  
  crm_db: 
    image: postgres:14
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
    volumes:
        - ./crm-db:/docker-entrypoint-initdb.d
        - ./postgres-crm-data:/var/lib/postgresql/data
        - ./crm-db/init-replication.sql:/docker-entrypoint-initdb.d/10-replication.sql  # добавляем скрипт репликации
    ports:
      - "5444:5432"
    networks:
      - bionicpro-network
  
  olap_db:
    image: clickhouse/clickhouse-server:latest
    environment:
      # - CLICKHOUSE_USER=default
      # - CLICKHOUSE_PASSWORD=default_pwd
      - CLICKHOUSE_DB=bionicpro
      - HOSTNAME=olap_db
    ports:
      - "8123:8123"
      - "9431:9000"
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse
      - ./olap-db:/docker-entrypoint-initdb.d
      - ./olap-db:/var/lib/clickhouse/user_files
      - ./olap-db/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./clickhouse/init-cdc.sql:/docker-entrypoint-initdb.d/10-cdc-init.sql  # Добавляем CDC инициализацию
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --user default --password default_pwd --query 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - bionicpro-network
  
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server --console-address ":9001" /data
    networks:
      - bionicpro-network

  postgres:
    image: postgres:16.0
    ports:
      - "5432:5432"
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - airflow
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - bionicpro-network

  airflow-webserver:
    <<: *airflow-common
    environment:
      <<: *airflow-environment
      HOSTNAME: airflow-webserver
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      olap_db:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    command: webserver
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  airflow-scheduler:
    <<: *airflow-common
    environment:
      <<: *airflow-environment
      HOSTNAME: airflow-scheduler
    command: scheduler
    depends_on:
      postgres:
        condition: service_healthy
      olap_db:
        condition: service_healthy
      airflow-webserver:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  airflow-triggerer:
    <<: *airflow-common
    environment:
      <<: *airflow-environment
      HOSTNAME: airflow-triggerer
    depends_on:
      postgres:
        condition: service_healthy
      olap_db:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    command: bash -c "airflow triggerer"
    healthcheck:
      test:
        - CMD-SHELL
        - airflow jobs check --job-type TriggererJob --hostname "${HOSTNAME}"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  airflow-cli:
    <<: *airflow-common
    environment:
      <<: *airflow-environment
      HOSTNAME: airflow-cli
    depends_on:
      postgres:
        condition: service_healthy
      olap_db:
        condition: service_healthy
    profiles:
      - debug
    command:
      - bash
      - -c
      - airflow

  airflow-init:
    <<: *airflow-common
    environment:
      <<: *airflow-environment
      HOSTNAME: airflow-init
    depends_on:
      postgres:
        condition: service_healthy
      olap_db:
        condition: service_healthy
    command: >
      bash -c "airflow db init && airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@sample.ru --password admin"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx_cache:/var/cache/nginx
    depends_on:
      - minio
    networks:
      - bionicpro-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - bionicpro-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - bionicpro-network

  debezium:
    image: debezium/connect:2.3.0.Final
    depends_on:
      - kafka
      - crm_db
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: crm-connect-cluster
      CONFIG_STORAGE_TOPIC: crm-connect-configs
      OFFSET_STORAGE_TOPIC: crm-connect-offsets
      STATUS_STORAGE_TOPIC: crm-connect-statuses
      CONNECT_CONFIG_PROVIDERS: "file"
      CONNECT_CONFIG_PROVIDERS_FILE_PATH: "/kafka/connect"
    ports:
      - "8083:8083"
    volumes:
      - ./connectors:/kafka/connect
    networks:
      - bionicpro-network

volumes:
  minio_storage: {}
  nginx_cache: {}

networks:
  bionicpro-network:
    driver: bridge
